"""Theme handlers package.

This module exports all available theme handlers for the prompt generator.
Handlers are organized by category in subfolders.
"""

# ============================================
# Animation Handlers
# ============================================
from .animation import (
    AnimeHandler,
    GhibliHandler,
    MangaHandler,
    WebtoonHandler,
    MechaHandler,
    ShonenHandler,
    RetroAnimeHandler,
    DisneyHandler,
    PixarHandler,
    DreamworksHandler,
    IlluminationHandler,
    LooneyTunesHandler,
    SouthParkHandler,
    MarvelHandler,
    DCComicsHandler,
    StopMotionHandler,
    ChibiHandler,
    ANIMATION_HANDLERS,
)

# ============================================
# Art Styles Handlers
# ============================================
from .art_styles import (
    AbstractHandler,
    ConceptArtHandler,
    MinimalistHandler,
    SurrealismHandler,
    PopArtHandler,
    ArtNouveauHandler,
    ArtDecoHandler,
    CubismHandler,
    ExpressionismHandler,
    ImpressionismHandler,
    BaroqueHandler,
    RenaissanceHandler,
    PsychedelicHandler,
    GlitchArtHandler,
    GraffitiHandler,
    FlatDesignHandler,
    PointillismHandler,
    FauvismHandler,
    RomanticismHandler,
    BauhausHandler,
    GothicArtHandler,
    StreetArtHandler,
    ART_STYLES_HANDLERS,
)

# ============================================
# Sketch & Drawing Handlers
# ============================================
from .sketch import (
    PencilSketchHandler,
    CharcoalHandler,
    InkDrawingHandler,
    BallpointPenHandler,
    BlueprintHandler,
    TechnicalDrawingHandler,
    ConteHandler,
    GraphiteHandler,
    GestureHandler,
    StipplingHandler,
    CalligraphyHandler,
    SKETCH_HANDLERS,
)

# ============================================
# Painting Handlers
# ============================================
from .painting import (
    OilPaintingHandler,
    WatercolorHandler,
    AcrylicHandler,
    GouacheHandler,
    InkWashHandler,
    PastelHandler,
    ColoredPencilHandler,
    SprayPaintHandler,
    CrayonHandler,
    FrescoHandler,
    TemperaHandler,
    EncausticHandler,
    DigitalPaintingHandler,
    MixedMediaHandler,
    ImpastoHandler,
    PAINTING_HANDLERS,
)

# ============================================
# 3D & Render Handlers
# ============================================
from .render_3d import (
    IsometricHandler,
    LowPolyHandler,
    ClayRenderHandler,
    WireframeHandler,
    VoxelHandler,
    UnrealEngineHandler,
    Stylized3DHandler,
    OctaneHandler,
    Cinema4DHandler,
    BlenderHandler,
    ProductRenderHandler,
    ArchVizHandler,
    Glass3DHandler,
    HolographicHandler,
    RENDER3D_HANDLERS,
)

# ============================================
# Photography Handlers
# ============================================
from .photography import (
    CinematicHandler,
    StudioPhotoHandler,
    StreetPhotoHandler,
    DocumentaryHandler,
    MacroHandler,
    LongExposureHandler,
    AerialDroneHandler,
    TiltShiftHandler,
    BokehHandler,
    DoubleExposureHandler,
    HDRHandler,
    BlackWhiteHandler,
    FilmGrainHandler,
    FoodPhotoHandler,
    SportsPhotoHandler,
    WildlifePhotoHandler,
    GoldenHourHandler,
    BlueHourHandler,
    SilhouetteHandler,
    PHOTOGRAPHY_HANDLERS,
)

# ============================================
# Portrait & People Handlers
# ============================================
from .portrait import (
    ClassicPortraitHandler,
    FineArtPortraitHandler,
    EnvironmentalPortraitHandler,
    MoodyPortraitHandler,
    DramaticPortraitHandler,
    EtherealHandler,
    FashionHandler,
    BeautyHandler,
    EditorialHandler,
    CorporateHandler,
    GlamourHandler,
    LifestyleHandler,
    FitnessHandler,
    BoudoirHandler,
    CosplayHandler,
    MaternityHandler,
    HeadshotHandler,
    CoupleHandler,
    GroupPhotoHandler,
    StreetStyleHandler,
    VintagePortraitHandler,
    CandidPortraitHandler,
    CharacterPortraitHandler,
    FilmPortraitHandler,
    PORTRAIT_HANDLERS,
)

# ============================================
# Animals & Creatures Handlers
# ============================================
from .animals import (
    CatHandler,
    DogHandler,
    WolfHandler,
    FoxHandler,
    HorseHandler,
    WildlifeArtHandler,
    PetsHandler,
    BirdsHandler,
    MarineLifeHandler,
    UnderwaterCreaturesHandler,
    InsectsHandler,
    DragonHandler,
    UnicornHandler,
    PhoenixHandler,
    DinosaurHandler,
    KaijuHandler,
    MythicalBeastsHandler,
    MermaidHandler,
    MonsterHandler,
    ANIMALS_HANDLERS,
)

# ============================================
# Sci-Fi Handlers
# ============================================
from .scifi import (
    CyberpunkHandler,
    SteampunkHandler,
    DieselpunkHandler,
    AtompunkHandler,
    SolarpunkHandler,
    BiopunkHandler,
    RaypunkHandler,
    SpaceOperaHandler,
    SpacecraftHandler,
    SpaceStationHandler,
    AlienWorldHandler,
    ColonyPlanetHandler,
    FuturisticCityHandler,
    NeonFutureHandler,
    AIDystopiaHandler,
    PostApocalypticHandler,
    RobotHandler,
    RetrofuturismHandler,
    HardSciFiHandler,
    PulpSciFiHandler,
    SCIFI_HANDLERS,
)

# ============================================
# Fantasy Handlers
# ============================================
from .fantasy import (
    EpicFantasyHandler,
    DarkFantasyHandler,
    HighFantasyHandler,
    LowFantasyHandler,
    UrbanFantasyHandler,
    GrimdarkHandler,
    FairyTaleHandler,
    SwordSorceryHandler,
    PortalFantasyHandler,
    WizardHandler,
    ElvenHandler,
    DwarvenHandler,
    GreekMythologyHandler,
    NorseMythologyHandler,
    CelticFantasyHandler,
    ArabianFantasyHandler,
    ArthurianHandler,
    WuxiaHandler,
    XianxiaHandler,
    IsekaiHandler,
    FANTASY_HANDLERS,
)

# ============================================
# Horror & Dark Handlers
# ============================================
from .horror import (
    VampireHandler,
    WerewolfHandler,
    ZombieHandler,
    WitchHandler,
    SlasherHandler,
    JHorrorHandler,
    PsychologicalHandler,
    BodyHorrorHandler,
    FolkHorrorHandler,
    SurvivalHorrorHandler,
    VictorianGothicHandler,
    SouthernGothicHandler,
    HauntedHandler,
    NightmareHandler,
    LovecraftianHandler,
    DemonicHandler,
    OccultHandler,
    CreepypastaHandler,
    HORROR_HANDLERS,
)

# ============================================
# Architecture Handlers
# ============================================
from .architecture import (
    ModernArchitectureHandler,
    BrutalistHandler,
    ArtDecoArchHandler,
    GothicCathedralHandler,
    JapaneseArchHandler,
    MediterraneanArchHandler,
    SkyscraperHandler,
    CastleHandler,
    TempleHandler,
    BridgeHandler,
    VictorianHouseHandler,
    IndustrialArchHandler,
    InteriorHandler,
    CityscapeHandler,
    VillageHandler,
    AbandonedHandler,
    ARCHITECTURE_HANDLERS,
)


# Export all handlers
__all__ = [
    # Animation
    'AnimeHandler',
    'GhibliHandler',
    'MangaHandler',
    'WebtoonHandler',
    'MechaHandler',
    'ShonenHandler',
    'RetroAnimeHandler',
    'DisneyHandler',
    'PixarHandler',
    'DreamworksHandler',
    'IlluminationHandler',
    'LooneyTunesHandler',
    'SouthParkHandler',
    'MarvelHandler',
    'DCComicsHandler',
    'StopMotionHandler',
    'ChibiHandler',
    # Art Styles
    'AbstractHandler',
    'ConceptArtHandler',
    'MinimalistHandler',
    'SurrealismHandler',
    'PopArtHandler',
    'ArtNouveauHandler',
    'ArtDecoHandler',
    'CubismHandler',
    'ExpressionismHandler',
    'ImpressionismHandler',
    'BaroqueHandler',
    'RenaissanceHandler',
    'PsychedelicHandler',
    'GlitchArtHandler',
    'GraffitiHandler',
    'FlatDesignHandler',
    'PointillismHandler',
    'FauvismHandler',
    'RomanticismHandler',
    'BauhausHandler',
    'GothicArtHandler',
    'StreetArtHandler',
    # Sketch & Drawing
    'PencilSketchHandler',
    'CharcoalHandler',
    'InkDrawingHandler',
    'BallpointPenHandler',
    'BlueprintHandler',
    'TechnicalDrawingHandler',
    'ConteHandler',
    'GraphiteHandler',
    'GestureHandler',
    'StipplingHandler',
    'CalligraphyHandler',
    # Painting
    'OilPaintingHandler',
    'WatercolorHandler',
    'AcrylicHandler',
    'GouacheHandler',
    'InkWashHandler',
    'PastelHandler',
    'ColoredPencilHandler',
    'SprayPaintHandler',
    'CrayonHandler',
    'FrescoHandler',
    'TemperaHandler',
    'EncausticHandler',
    'DigitalPaintingHandler',
    'MixedMediaHandler',
    'ImpastoHandler',
    # 3D & Render
    'IsometricHandler',
    'LowPolyHandler',
    'ClayRenderHandler',
    'WireframeHandler',
    'VoxelHandler',
    'UnrealEngineHandler',
    'Stylized3DHandler',
    'OctaneHandler',
    'Cinema4DHandler',
    'BlenderHandler',
    'ProductRenderHandler',
    'ArchVizHandler',
    'Glass3DHandler',
    'HolographicHandler',
    # Photography
    'CinematicHandler',
    'StudioPhotoHandler',
    'StreetPhotoHandler',
    'DocumentaryHandler',
    'MacroHandler',
    'LongExposureHandler',
    'AerialDroneHandler',
    'TiltShiftHandler',
    'BokehHandler',
    'DoubleExposureHandler',
    'HDRHandler',
    'BlackWhiteHandler',
    'FilmGrainHandler',
    'FoodPhotoHandler',
    'SportsPhotoHandler',
    'WildlifePhotoHandler',
    'GoldenHourHandler',
    'BlueHourHandler',
    'SilhouetteHandler',
    # Portrait & People
    'ClassicPortraitHandler',
    'FineArtPortraitHandler',
    'EnvironmentalPortraitHandler',
    'MoodyPortraitHandler',
    'DramaticPortraitHandler',
    'EtherealHandler',
    'FashionHandler',
    'BeautyHandler',
    'EditorialHandler',
    'CorporateHandler',
    'GlamourHandler',
    'LifestyleHandler',
    'FitnessHandler',
    'BoudoirHandler',
    'CosplayHandler',
    'MaternityHandler',
    'HeadshotHandler',
    'CoupleHandler',
    'GroupPhotoHandler',
    'StreetStyleHandler',
    'VintagePortraitHandler',
    'CandidPortraitHandler',
    'CharacterPortraitHandler',
    'FilmPortraitHandler',
    # Animals & Creatures
    'CatHandler',
    'DogHandler',
    'WolfHandler',
    'FoxHandler',
    'HorseHandler',
    'WildlifeArtHandler',
    'PetsHandler',
    'BirdsHandler',
    'MarineLifeHandler',
    'UnderwaterCreaturesHandler',
    'InsectsHandler',
    'DragonHandler',
    'UnicornHandler',
    'PhoenixHandler',
    'DinosaurHandler',
    'KaijuHandler',
    'MythicalBeastsHandler',
    'MermaidHandler',
    'MonsterHandler',
    # Sci-Fi
    'CyberpunkHandler',
    'SteampunkHandler',
    'DieselpunkHandler',
    'AtompunkHandler',
    'SolarpunkHandler',
    'BiopunkHandler',
    'RaypunkHandler',
    'SpaceOperaHandler',
    'SpacecraftHandler',
    'SpaceStationHandler',
    'AlienWorldHandler',
    'ColonyPlanetHandler',
    'FuturisticCityHandler',
    'NeonFutureHandler',
    'AIDystopiaHandler',
    'PostApocalypticHandler',
    'RobotHandler',
    'RetrofuturismHandler',
    'HardSciFiHandler',
    'PulpSciFiHandler',
    # Fantasy
    'EpicFantasyHandler',
    'DarkFantasyHandler',
    'HighFantasyHandler',
    'LowFantasyHandler',
    'UrbanFantasyHandler',
    'GrimdarkHandler',
    'FairyTaleHandler',
    'SwordSorceryHandler',
    'PortalFantasyHandler',
    'WizardHandler',
    'ElvenHandler',
    'DwarvenHandler',
    'GreekMythologyHandler',
    'NorseMythologyHandler',
    'CelticFantasyHandler',
    'ArabianFantasyHandler',
    'ArthurianHandler',
    'WuxiaHandler',
    'XianxiaHandler',
    'IsekaiHandler',
    # Horror & Dark
    'VampireHandler',
    'WerewolfHandler',
    'ZombieHandler',
    'WitchHandler',
    'SlasherHandler',
    'JHorrorHandler',
    'PsychologicalHandler',
    'BodyHorrorHandler',
    'FolkHorrorHandler',
    'SurvivalHorrorHandler',
    'VictorianGothicHandler',
    'SouthernGothicHandler',
    'HauntedHandler',
    'NightmareHandler',
    'LovecraftianHandler',
    'DemonicHandler',
    'OccultHandler',
    'CreepypastaHandler',
    # Architecture
    'ModernArchitectureHandler',
    'BrutalistHandler',
    'ArtDecoArchHandler',
    'GothicCathedralHandler',
    'JapaneseArchHandler',
    'MediterraneanArchHandler',
    'SkyscraperHandler',
    'CastleHandler',
    'TempleHandler',
    'BridgeHandler',
    'VictorianHouseHandler',
    'IndustrialArchHandler',
    'InteriorHandler',
    'CityscapeHandler',
    'VillageHandler',
    'AbandonedHandler',
]

# Combined handler class mapping for ThemeRegistry
HANDLER_CLASSES = {
    **ANIMATION_HANDLERS,
    **ART_STYLES_HANDLERS,
    **SKETCH_HANDLERS,
    **PAINTING_HANDLERS,
    **RENDER3D_HANDLERS,
    **PHOTOGRAPHY_HANDLERS,
    **PORTRAIT_HANDLERS,
    **ANIMALS_HANDLERS,
    **SCIFI_HANDLERS,
    **FANTASY_HANDLERS,
    **HORROR_HANDLERS,
    **ARCHITECTURE_HANDLERS,
}
